# Generated by Django 3.1.2 on 2020-11-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contrseña', models.CharField(max_length=50)),
                ('nombreC', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
