# Generated by Django 3.1.2 on 2020-11-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0002_rusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('contrseña', models.CharField(max_length=50)),
                ('nombreC', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='rusuario',
        ),
    ]
